In [1]:
import numpy as np

In [2]:
# №1 Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.
a = np.ones((10, 10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [3]:
# №2 Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [4]:
# №3 Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули
x = np.diag([1,2,3,4],k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [5]:
# №4 Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее по каждой строке было в точности ноль.
a = np.random.random((5, 5))
current_sum = 0
for i in range(0,5):
  for j in range(0,5):
    current_sum+=a[i,j]
  a[i] = a[i] - current_sum/5
  current_sum = 0
print (a)
#проверим, получатся очень маленькие числа, почти нули:
for i in range(0,5):
  for j in range(0,5):
    current_sum += a[i,j]
  print (current_sum)
  current_sum = 0

[[ 0.13485184 -0.32927414  0.37385542 -0.08838827 -0.09104486]
 [-0.15988681 -0.06318831  0.47370255 -0.06460622 -0.18602121]
 [-0.24466025  0.10538372 -0.05616756  0.13216439  0.06327969]
 [ 0.00194452  0.03561395  0.11475473 -0.2189811   0.0666679 ]
 [-0.09900147  0.27143781 -0.22518242 -0.26888427  0.32163035]]
0.0
-5.551115123125783e-16
0.0
0.0
-1.1102230246251565e-16


In [6]:
# №5 Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.
a = np.random.random((10, 3))
operation_result= []

for i in range(0,10):
  min_value = a[i,0]
  for j in range(0,3):
    if abs(a[i,j]-0.5) < abs(min_value-0.5):
      min_value = a[i,j]
  operation_result.append(min_value)
  min_value = 0.5
print(a)
print(operation_result)

[[0.69284014 0.6929507  0.26694314]
 [0.39382367 0.70946937 0.83745111]
 [0.83906904 0.46600299 0.80062191]
 [0.3487976  0.45658602 0.30674936]
 [0.14692071 0.42871    0.11966362]
 [0.69835265 0.92078215 0.94721403]
 [0.83383364 0.65548279 0.42005403]
 [0.21731865 0.30103053 0.87454499]
 [0.34568748 0.74855989 0.90256537]
 [0.78842305 0.92392971 0.02980667]]
[0.6928401381975713, 0.39382367026213283, 0.4660029853231291, 0.4565860199393602, 0.4287099981362711, 0.6983526464605803, 0.4200540257620121, 0.3010305260800722, 0.3456874761771407, 0.7884230519152862]


In [7]:
# №6 Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.
x = np.random.random((6, 6))
print(x)
for i in range(6):
  print(sum(x[i])/max((x[j][i] for j in range(6))))


[[0.54621428 0.00739077 0.22882311 0.13471608 0.36782776 0.71537166]
 [0.80647658 0.57802174 0.47535032 0.48779438 0.20575086 0.36777178]
 [0.39860281 0.35817556 0.49575035 0.35255913 0.31440852 0.05497929]
 [0.19830262 0.5121053  0.56261573 0.37155602 0.91346422 0.78629373]
 [0.44982741 0.73913553 0.15996341 0.20084943 0.28763436 0.83912301]
 [0.12202138 0.61908066 0.66648058 0.60319775 0.32194856 0.30644037]]
2.4803493373768495
3.952138081387988
2.9625404054669717
5.54434700512731
2.930090832749535
3.1451518778274576


In [8]:
# №7 На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(max((x[i] for i in range(1, len(x)) if x[i - 1] == 0)))

5


In [9]:
# №8 Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i.
# В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
  x[j] += 1
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [10]:
#Задача со звездочкой.

#Создайте произвольный двумерный массив NxM, N, M > 1. На его основе создайте новый двумерный массив, значения в котором являются средним значением исходного во всевозможных окошках размера 2х2 со сдвигом 1 по вертикали и горизонтали.
P = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])
A = np.array([(b[0, 0] + b[0, 1] + b[1, 0] + b[1, 1])/4 for a in np.lib.stride_tricks.sliding_window_view(P, (2, 2)) for b in a]).reshape(len(P[0:, 0])-1, len(P[0, 0:])-1)
print(A)

[[ 5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5]
 [15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5]
 [25.5 26.5 27.5 28.5 29.5 30.5 31.5 32.5 33.5]]
